### ISSUE TITLE
LUA Error 'ADDON_ACTION_FORBIDDEN' when opening adventure guide

### ISSUE THREAD

**Issue by fzarr** [teelolws/MplusAG#14]
4x [ADDON_ACTION_FORBIDDEN] AddOn 'MplusAdventureGuide' tried to call the protected function 'OnOpen()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `OnOpen'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:587: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:576>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2943: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2786: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2651: in function <FrameXML/UIParent.lua:2647>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3253: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:3214: in function `ToggleFrame'
[string "@FrameXML/UIParent.lua"]:1150: in function `ToggleEncounterJournal'
[string "TOGGLEENCOUNTERJOURNAL"]:1: in function <[string "TOGGLEENCOUNTERJOURNAL"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

**Comment by teelolws** [comment]
Thanks. This should sort it. Let me know if it keeps happening, and if possible, if you can find a consistent set of button clicks that always sets it off after a /reload
