### ISSUE TITLE
New M+ Key Lvl conceales view to other Weakaura/Addons

### ISSUE THREAD

**Issue by Dezarius** [teelolws/MplusAG#15]
Hey. Ty for addin the new mouseover teleport buttons. They are awesome! But can you place add an option to hide the dungeon lvl that i completed? i use another weak aura to change the asthetics and show both fort and tyr key lvl at the same time and the new number gets shown above of them. So would be really nice if i can deactivate the number in this addon. ty!

**Comment by teelolws** [comment]
Possibly. However, do you really care what your highest Tyrannical level is on a Fortified week? Could you not remove that part of the weakaura instead? The addon will show you the highest you have completed based on whether this week is Tyrannical or Fortified!

**Comment by Dezarius** [comment]
hey! ty for the answer. but i prefere it just as an overview. and i really prefere the design. i can customize it and make it exactly the way i want it. only the new number is in the way xD.

**Comment by teelolws** [comment]
Options added:
![image](https://github.com/teelolws/MplusAG/assets/49792789/4afdb6c1-36f9-4146-8a1f-6e109142eafa)

**Comment by Dezarius** [comment]
WOW! nice ty !!!
