### ISSUE TITLE
Lua Error  Watermark DB

### ISSUE THREAD

**Issue by Dezarius** [teelolws/MplusAG#17]
Hey. sorry to bother you again. but after the last update i get a lua error when starting game /reloading:

`
Message: Interface/AddOns/MplusAdventureGuide/watermark.lua:4: attempt to index field 'db' (a nil value)
Time: Thu Jun 15 17:13:22 2023
Count: 1
Stack: Interface/AddOns/MplusAdventureGuide/watermark.lua:4: attempt to index field 'db' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/MplusAdventureGuide/watermark.lua"]:4: in function <Interface/AddOns/MplusAdventureGuide/watermark.lua:3>
[string "@Interface/SharedXML/EventUtil.lua"]:74: in function <Interface/SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:178: in function <Interface/SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/SharedXML/GlobalCallbackRegistry.lua"]:9: in function <Interface/SharedXML/GlobalCallbackRegistry.lua:8>

Locals: (*temporary) = <function> defined =[C]:-1
`
seems like it can't find db for the watermark system.

**Comment by teelolws** [comment]
Nah, its trying to load in the watermark system before its loaded in the options table. I guess I can't trust `EventUtil.ContinueOnAddOnLoaded` to run in the order I called it. I'll have to refactor some of the code.
