### ISSUE TITLE
Bug popping up while opening the M+ Dungeon window

### ISSUE THREAD

**Issue by Avarkus** [teelolws/MplusAG#23]
> 1x MplusAdventureGuide/portal-buttons.lua:166: bad argument #1 to 'ipairs' (table expected, got nil)
> [string "=[C]"]: in function `ipairs'
> [string "@MplusAdventureGuide/portal-buttons.lua"]:166: in function <MplusAdventureGuide/portal-buttons.lua:158>
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> 
> Locals:
> (*temporary) = nil
> (*temporary) = "table expected, got nil"
>  = <function> defined =[C]:-1

 
 It's not game breaking. I'm still able to use my portals and such when I open the M+ Dungeon window, but this bug pops up everytime.

**Comment by teelolws** [comment]
Whoops. Got it, thanks.
