### ISSUE TITLE
Suggestion: Add Dungeon Name/Abbreviation to icon

### ISSUE THREAD

**Issue by syrifgit** [teelolws/MplusAG#24]
Hi, I just came across your addon and I think it can replace 2 massive weakauras I currently use. 1 for teleports, and 1 for displaying key levels.

I think showing the name / abbreviation (RLP, HOI, BH, etc) on the icon is the only thing missing compared to these 2 weakauras.

Great addon! Cheers.

**Comment by teelolws** [comment]
Can you show me a picture or link the weakaura?

**Comment by syrifgit** [comment]
Here is an example: https://wago.io/QXJ4dN6pp

**Comment by teelolws** [comment]
Hows this?
![image](https://github.com/teelolws/MplusAG/assets/49792789/54ff93b6-c37f-4d9c-9c3d-adcec0acf344)

**Comment by syrifgit** [comment]
Looks very good! Just updated and checked in game. Cheers for being an active / receptive dev. :)

Quick question while I am here ... the keystone levels shown, up top coloured, and on bottom in brackets. Is there a way to make it always show the 2 different affixes?

For some of my keys, it is showing fortified for both numbers, because it's fort week and my tyrannical is lower. Is there a way to make it so the top row is **_always_** the current affix highest key, and the bottom is **_always_** the opposite affix highest key? Am I missing something?

**Comment by teelolws** [comment]
Top is part of the base UI - it is the highest you have completed. The bottom is what I added: the highest you have completed on the current week's affix. This is just how I wanted it, it conveys the most useful information for the current week. You can still see the other week when you mouseover and look at the tooltip!
