### ISSUE TITLE
Conflict with addon "Inactive Reputation Headers"

### ISSUE THREAD

**Issue by F-Lambda** [teelolws/MplusAG#26]
When both this addon and [Inactive Reputation Headers](https://www.curseforge.com/wow/addons/inactive-reputation-headers) are enabled, attempting to transfer currency fails with the message:

![image](https://github.com/user-attachments/assets/d54928aa-b10a-4245-939f-e101da6e5611)

Using either addon by themself causes no issue. Tested with these two addons being the only two loaded.

Inactive Reputation Headers veresion: r34 (2024-07-27)
M+ Adventure Guide version: 11.0-005 (2024-07-27)

**Comment by teelolws** [comment]
I don't have much time for testing right now. Can you confirm if this fix works?

**Comment by F-Lambda** [comment]
That seemed to fix it, yeah
